### ISSUE TITLE
Upgrade the operator base image

### ISSUE THREAD

**Issue by ormergi** [kubevirt/cluster-network-addons-operator#1129]
**What happened**:
Currently CNAO container base image is centos 7, we should consider upgrading it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by phoracek** [comment]
Done via https://github.com/kubevirt/cluster-network-addons-operator/pull/1142
