### ISSUE TITLE
Create a github-action to prepare a release branch

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cluster-network-addons-operator#1154]
**What happened**:

When a release branch is created at CNAO the following steps need to be done:
- Push the branch to the repo
- Change components.yaml to static at components without a release branch
- Create prow jobs for it.
- Create autobumper config.
- add gerrit m/s patch to follow the stable branch on relevant m/s branch

This is very error prone and we have suffer a lot from it.

**What you expected to happen**:
A github-action should run when a release-x.y branch is pushed creating a pair or PRs
- A PR at CNAO to change components.yaml to static 
- A PR at project-infra creating the prow jobs for the release branch

**Notes**:
We can also use the github actions `workflow_distpatch` so users can create releases and release branches directly from github UI or gh cli.

**Comment by RamLavi** [comment]
This PR automates at least some of the requested above https://github.com/kubevirt/cluster-network-addons-operator/pull/1322

It doesn't tackle these out-of-repo AIs:
- Create prow jobs for it.
- add gerrit m/s patch to follow the stable branch on relevant m/s branch
