### ISSUE TITLE
[release-0.53] Fix ovs-cni lane

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cluster-network-addons-operator#1196]
**What happened**:

The ovs-cni lane is not working with latest kubevirtci but we needed to install ovs https://github.com/kubevirt/cluster-network-addons-operator/pull/1166.

**What you expected to happen**:

The lane should work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by RamLavi** [comment]
release-0.53's ovs-cni version is [v0.19.6](https://github.com/kubevirt/cluster-network-addons-operator/blob/release-0.53/components.yaml#L43 ) 
Do we need to bump kubevirtci on ovs-cni's stable branch [release-0.19](https://github.com/k8snetworkplumbingwg/ovs-cni/commits/release-0.19)?

**Comment by RamLavi** [comment]
@qinqon I am thinking on cherry-picking [this PR](https://github.com/k8snetworkplumbingwg/ovs-cni/pull/221) to [release-0.19](https://github.com/k8snetworkplumbingwg/ovs-cni/commits/release-0.19) branch, with the small change [here](https://github.com/k8snetworkplumbingwg/ovs-cni/pull/221/files#diff-371370cbcaca5626463701e7a1886464ae8b4be500e989cc886c5d9ffa5e88faR15) of bumping to 1.21 and not to 1.23. 

what do you think?

**Comment by qinqon** [comment]
> @qinqon I am thinking on cherry-picking [this PR](https://github.com/k8snetworkplumbingwg/ovs-cni/pull/221) to [release-0.19](https://github.com/k8snetworkplumbingwg/ovs-cni/commits/release-0.19) branch, with the small change [here](https://github.com/k8snetworkplumbingwg/ovs-cni/pull/221/files#diff-371370cbcaca5626463701e7a1886464ae8b4be500e989cc886c5d9ffa5e88faR15) of bumping to 1.21 and not to 1.23.
> 
> what do you think?

Fine by me, let's try it out.

**Comment by phoracek** [comment]
release-0.53 is over a year old and will be retired soon. I would suggest that for this release, we don't bother with OVS backports. If CI fails on `Panic: runtime error: slice bounds out of range [2:1]` there, it should be safe to skip.

Thoughts @RamLavi @qinqon ?
