### ISSUE TITLE
Installation link in releases is broken

### ISSUE THREAD

**Issue by amostech** [kubevirt/cluster-network-addons-operator#1299]
**What happened**:
kubectl apply -f https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.65.5/operator.yaml
kubectl apply -f https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.65.5/network-addons-config.crd.yaml
kubectl apply -f https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.65.5/namespace.yaml

  error: unable to read URL "https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.65.5/operator.yaml", server reported 404 Not Found, status code=404

**What you expected to happen**:
Installation links pointed to the correct release yaml files. 

**How to reproduce it (as minimally and precisely as possible)**:
Run the commands as shown in the install guide on the Github Releases page

**Anything else we need to know?**:

**Environment**:
On prem bare metal kubernetes cluster

**Comment by amostech** [comment]
Basically the link in the releases page points to a non-existent URL: https://github.com/kubevirt/cluster-network-addons-operator/releases/download/<VERSION>/namespace.yaml

Am I missing something here?

**Comment by amostech** [comment]
For anyone looking for this... looked into the repo itself and found a manifests folder. This seem to have worked for me. 

```
kubectl apply -f https://raw.githubusercontent.com/kubevirt/cluster-network-addons-operator/main/manifests/cluster-network-addons/0.72.0/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/kubevirt/cluster-network-addons-operator/main/manifests/cluster-network-addons/0.72.0/network-addons-config.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/kubevirt/cluster-network-addons-operator/main/manifests/cluster-network-addons/0.72.0/operator.yaml
```

**Comment by phoracek** [comment]
Ouch, thanks for reporting this.

@qinqon if you'd find some time, could you fix the release script?

**Comment by phoracek** [comment]
Nevermind, @RamLavi is looking into this

**Comment by RamLavi** [comment]
uploaded the manifests manually to the releases it failed so you should be able to run it now.
opened another issue to fix the failed job https://github.com/kubevirt/cluster-network-addons-operator/issues/1301

closing this one
