### ISSUE TITLE
files not uploaded to githubs's release assets on new releases

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/cluster-network-addons-operator#1301]
**What happened**:
prow job `release-cluster-network-addons-operator` is consistently failing from v0.70.0 failing on prow ([link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/release-cluster-network-addons-operator/1506657233256058880))
This means that no files are getting uploaded to the release.

**What you expected to happen**:
release files to upload to new releases

**How to reproduce it (as minimally and precisely as possible)**:
it's doesn't happen

**Anything else we need to know?**:
I manually uploaded the files in the releases where the jobs failed.

**Environment**:

**Comment by RamLavi** [comment]
@qinqon can you take a look?

**Comment by qinqon** [comment]
> @qinqon can you take a look?

Sure

**Comment by RamLavi** [comment]
perhaps the new gitActions is opening the branch in a different naming, so that project-infra doesn't catch it? (see [here](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml#L7))

gitActions release PRs have branches with name like `v0.73.0` (see [here](https://github.com/kubevirt/cluster-network-addons-operator/pull/1304))
but PRs from the pre-gitAction era were named like this: `RamLavi:release-0.56.0` (see [here](https://github.com/kubevirt/cluster-network-addons-operator/pull/880))

**Comment by qinqon** [comment]
Yep, it should catch branches or tags with same name, but better not to use the same name, this shoul fix it https://github.com/kubevirt/cluster-network-addons-operator/pull/1286

**Comment by RamLavi** [comment]
ack. Let's see in the next release

**Comment by RamLavi** [comment]
FYI update manually for [v0.73.0](https://github.com/kubevirt/cluster-network-addons-operator/releases/tag/v0.73.0)

on [v0.74.0](https://github.com/kubevirt/cluster-network-addons-operator/releases/tag/v0.74.0) I do see the files.. does it mean it is fixed or did you do it manually as well?

**Comment by jbpratt** [comment]
v0.75.0 and v0.76.0 are both missing assets

**Comment by RamLavi** [comment]
> v0.75.0 and v0.76.0 are both missing assets

updated now. @qinqon seems like it's still not working
