### ISSUE TITLE
Missing assets in latest releases

### ISSUE THREAD

**Issue by EdDev** [kubevirt/cluster-network-addons-operator#1353]
**What happened**:
Since v0.75.0 release, only the source code is included in the release assets.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by RamLavi** [comment]
duplicate of https://github.com/kubevirt/cluster-network-addons-operator/issues/1301

Updated assets
