### ISSUE TITLE
[flaky] lifecycle lane fails on specific release 0.69.0 

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/cluster-network-addons-operator#1487]
**What happened**:
test `lifecycle Test Suite: [It] Cluster Network Addons Operator when operator in version 0.69.0 is installed and supported spec configured and it is upgraded to the latest release it should report expected deployed container images and leave no leftovers from the previous version ` is flaky

prow link: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1486/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1604715178362933248

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by RamLavi** [comment]
@qinqon do we want to support such an old version?

**Comment by RamLavi** [comment]
it looks like `bridge-marker` and `ovs-cni-marker` daemonsets are stuck due to:
```
Events:
  Type     Reason            Age                From                  Message
  ----     ------            ----               ----                  -------
  Warning  FailedCreate      34s (x2 over 34s)  daemonset-controller  Error creating: pods "bridge-marker-" is forbidden: error looking up service account cluster-network-addons/bridge-marker: serviceaccount "bridge-marker" not found```

**Comment by oshoval** [comment]
do we need to reopen or it was solved?
