### ISSUE TITLE
Crashing OVS CNI Marker pods due to Segfault

### ISSUE THREAD

**Issue by MarkSpencerTan** [kubevirt/cluster-network-addons-operator#1498]
**What happened**:
I deployed the OVS CNI using the cluster-network-addons-operator and it deployed it successfully, however, I've noticed at random intervals the OVS CNI pods would crash with a segmentation fault error like below:

```bash
ovs-cni-marker qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
I've noticed the random crashes only happens for the ARM nodes in our cluster. The amd64 ones are ok.
Does anyone know the cause of this or any fix? Thanks so much

**What you expected to happen**:
OVS CNI pods would not crash

**How to reproduce it (as minimally and precisely as possible)**:
Have a cluster with arm nodes
Install OVS CNI with ClusterNetworkAddons, and then wait until the pods crash with no other error

**Environment**:
Kubernetes 1.22.16
Cluster Network Addons Version: v0.79.1

**Comment by oshoval** [comment]
Maybe related https://github.com/docker/for-mac/issues/6204#issuecomment-1054310263 ?
