### ISSUE TITLE
Rename NetworkAddonsConfig(s) to NetworkAddon(s)

### ISSUE THREAD

**Issue by phoracek** [kubevirt/cluster-network-addons-operator#15]
Let's save a little bit of space and time (pronouncing it) and rename `NetworkAddonsConfig` object to `NetworkAddons`. That would mimic KubeVirt and CDI operators with their `KubeVirt` and `CDI` objects.

On the other hand, it does not follow OpenShift operator naming. But I would not mind that that much, since we don't really follow OpenShift operator concept at all (with service objects, openshift operator state reporting etc).

Opinions @booxter @SchSeba?

**Comment by booxter** [comment]
Yes please.

**Comment by phoracek** [comment]
All right, then let's do this once #8 and #14 are merged.

**Comment by phoracek** [comment]
@booxter @SchSeba there is just one problem. Every CRD needs singular and plural name. Now it is `networkaddonsconfig` and `networkaddonsconfigs`. With this proposed change, the new singular `networkaddons` prevents us from having reasonable and expected plural. We can try to hack around that, but it is a hassle, since many code generating tools (...) don't expect that. The other option would be naming the object `NetworkAddon`, which would satisfy Kubernetes, but IMO does not make much sense.

**Comment by dankenigsberg** [comment]
Are we renaming the whole operator, or just its lower-level config?

I have never given much thought about either name. Is the problem here the mere length of the existing CR name? To me it does not seem *that* long. But I'm not going out often.

What is the name used by OpenShift's operator for its PR?

**Comment by phoracek** [comment]
I see that OpenShift network operator did some renaming recently. They name both of their resources just `Network` (each in different group): https://github.com/openshift/cluster-network-operator#example-configurations

Then most of their operator repositories are cluster-*-operator, not all of them though. I'd like to drop `cluster-` from this one, but that is not in the scope of this issue.

There is just one level of configuration now (if we add a second one, this current one will be lower).

The length is not a big problem, just that it is unnecessary long.

**Comment by dankenigsberg** [comment]
> I see that OpenShift network operator did some renaming recently. They name both of their resources just `Network` (each in different group): https://github.com/openshift/cluster-network-operator#example-configurations

Ouch, I find it very confusing.

> 
> Then most of their operator repositories are `cluster-*-operator`, not all of them though. I'd like to drop `cluster-` from ours, but that is not in the scope of this issue.
> 
> There is just one level of configuration now (if we add a second one, this current one will be lower).
> 
> The length is not a big problem, just that it is unnecessary long.

So I personally do not understand yet the need to rename. Do you find the following ideas helpful? NetworkExtra(s) NetworkFrill(s) NetworkSupplement(s)
https://www.merriam-webster.com/thesaurus/add-on is your friend.

**Comment by phoracek** [comment]
With my limited vocabulary, none of those beats NetworkAddon(s) (even though it is a bit misleading in singular).

One reason for renaming would be to make it more minimalistic and appealing (but maybe that's just me). Another reason might be that we don't really keep config in the object, just provide a simple way to deploy those components.

Maybe @booxter and @SchSeba have more specific reasons in mind.

**Comment by phoracek** [comment]
I don't see this happening anymore, closing the issue. If someone is against, feel free to reopen.
