### ISSUE TITLE
RFE - add ovn-kubernetes as a component

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/cluster-network-addons-operator#1549]
**What happened**:
Now that [OVN-Kubernetes ](https://github.com/ovn-org/ovn-kubernetes) is a multi-homed CNI, it could be of great benefit for the KubeVirt ecosystem to have it integrated into CNAO given the features available for secondary networks (and more coming ...):
- secondary overlays (no k8s node configuration required)
- localnet networks (node configuration required)
- multi-networks policies (currently in the works)
- services (in the roadmap ...)

To make matters clear, this RFE is only about secondary networks; in no way are we planning on using CNAO to manipulate the cluster's default network or its configuration.

**Comment by phoracek** [comment]
This sounds great! I think that shipping OVN Kubernetes as a solution for additional networks would be a great benefit, especially for the advanced cloud native use-cases you have listed.

One condition I would set is that this does not affect the primary CNI (it should not reconfigure default network on nodes, it should not touch the CNI config on hosts, ...).

**Comment by maiqueb** [comment]
> This sounds great! I think that shipping OVN Kubernetes as a solution for additional networks would be a great benefit, especially for the advanced cloud native use-cases you have listed.
> 
> One condition I would set is that this does not affect the primary CNI (it should not reconfigure default network on nodes, it should not touch the CNI config on hosts, ...).

Yes, I agree. I'll add this info into the RFE's description. 

Thanks for ensuring the clarity of the request.

**Comment by oshoval** [comment]
Hi, i am trying to learn the ropes and hopefully work on this feature once needed

Do you have maybe please what need to be done in order to not cause a conflict between OVN-K and Calico (that we are using on kubevirtci vm based providers)
Maybe the network segment / affected namespaces need to be changed?
Thanks

**Comment by maiqueb** [comment]
> Hi, i am trying to learn the ropes and hopefully work on this feature if / once needed
> 
> Do you have maybe please what need to be done in order to not cause a conflict between OVN-K and Calico (that we are using on kubevirtci vm based providers) Maybe the network segment / affected namespaces need to be changed?
> 
> using this killed the cluster, i guess due to a conflict of the net-cidr ? (some pods got restarted and then cluster died)
> 
> ```
> ./daemonset.sh --image=quay.io/oshoval/ovn-daemonset-f:latest \
>     --net-cidr=192.168.0.0/16/24 --svc-cidr=172.16.1.0/24 \
>     --gateway-mode="local" \
>     --k8s-apiserver=https://192.168.66.101:6443
> ```
> 
> Thanks

No idea, I haven't tried.

All I can say is I don't think you would need to define the svc-cidr: that's a default cluster network feature. Maybe you *need* because the ovn-k images assume they own the cluster default network ? ... Not sure.

**Comment by oshoval** [comment]
btw a greedy solution can be to move to kind when using CNAO if you wish
as we know that with kind it can be deployed (according https://kubevirt.io/2023/OVN-kubernetes-secondary-networks.html)

note that atm, we should not update kubevirtci provider version until https://github.com/kubevirt/kubevirtci/issues/1048 is fixed
