### ISSUE TITLE
ARM: Track U/S components multi arch images status

### ISSUE THREAD

**Issue by oshoval** [kubevirt/cluster-network-addons-operator#1599]
**What happened**:
Following https://github.com/kubevirt/cluster-network-addons-operator/issues/1498
It seems we need to create multi arch images once we want to fully support ARM
Lets use this issue to track CNAO's component, to see which is built multi arch
or any other issue on ARM if we decide to have it here.

- [ ] KubeMacPool
- [ ] Ovs-CNI
- [ ] MultusDynamicNetworks
- [ ] MacvTap
- [ ] Bridge-marker
- [ ] KubeSecondaryDNS

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by aarnaud** [comment]
Still an issue, just got it
