### ISSUE TITLE
Deployment of multus-dynamic-networks-controller on OpenShift

### ISSUE THREAD

**Issue by orelmisan** [kubevirt/cluster-network-addons-operator#1602]
**What happened**:
Currently, CNAO blocks the deployment of `multus-dynamic-networks-controller` on OpenShift.
CNAO configures (in three places) the Multus socket path to `/run/multus/multus.sock` which is incorrect.
Also, CNAO does not deploy the [required SCC](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/8e060251899f99e68c312e6b97d2a585d0a0fc72/manifests/scc.yaml#L1).

**What you expected to happen**:
CNAO should allow the deployment of `multus-dynamic-networks-controller` on OpenShift.
CNAO should configure the Multus socket path to `/run/multus/socket/multus.sock`.
CNAO should deploy the required SCC.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
OpenShift

**Comment by oshoval** [comment]
Hi,
Wasn'y this one fixed already ?
if so please close

**Comment by orelmisan** [comment]
> Hi, Was this one fixed already ? if so please close

Not that I know of.
I don't regularly follow this repo.
