### ISSUE TITLE
Auto bump fails because of multus component

### ISSUE THREAD

**Issue by oshoval** [kubevirt/cluster-network-addons-operator#1813]
**What happened**:
https://github.com/kubevirt/cluster-network-addons-operator/actions/runs/9642633059

It fails because it can't find the commit associated to the tag.
The reason is we are fetching 100 commits, and atm the required commit is far from HEAD
by 109 commits.
`git rev-list --count f03765681fe81ee1e0633ee1734bf48ab3bccf2b..HEAD`
We should use pagination, because max per page is 100 (`getLatestTaggedFromBranch`)
https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits

**What you expected to happen**:
Bump should work even if the commit is far away.
Alternatively we can do rev-parse / rev-list by the tag to its hash maybe ?

For example this works from CLI, we can check the code version of it
```
git rev-list -n1 v4.0.2
f03765681fe81ee1e0633ee1734bf48ab3bccf2b
```
instead of (this code otherwise need pagination)
```
		for _, commit := range branchCommits {
			if commit.GetSHA() == commitShaOfTag {
				return tagName, commit.GetSHA(), nil
			}
		}
```

**How to reproduce it (as minimally and precisely as possible)**:
Just check the bump and see multus fails.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by oshoval** [comment]
Hi @RamLavi 
Any reason why not just use rev-parse / rev-list
given the tag, fetch its commit and compare it to the expected one?
Otherwise we would need pagination and iterate over all the commits, trying to find one matching the expected commit
as we do now but with additional pagination.
The logic seems redundant.

**Comment by RamLavi** [comment]
Hey @oshoval 
Are you offering changing the library function with an "exec" equivalent?

**Comment by oshoval** [comment]
Hi
I suggest a `rev-list` equivalent library call if exists
about exec we can consider at worse case, or to do the pagination

Scope of code change is just this code:
```
		for _, commit := range branchCommits {
			if commit.GetSHA() == commitShaOfTag {
				return tagName, commit.GetSHA(), nil
			}
		}
```

**Comment by RamLavi** [comment]
I suggest not use "exec". We worked hard in order to use go libraries and not write another bash script that cannot be unit tested as easily. 
AFAIR at the time there was no "rev-list" equivalent, but maybe now there is. IIRC the need for this loop is to catch both types of "tag" types.

**Comment by oshoval** [comment]
> I suggest against using "exec". We worked hard in order to use go libraries and not write another bash script that cannot be unit tested as easily. AFAIR at the time there was no "rev-list" equivalent, but maybe now there is. IIRC the need for this loop is to catch both types of "tag" types.

what are the two types please ?

we can also consider this (using library)
```
We can also do the following with library if exists:
Given the expected SHA, check a describe on that SHA to see it match the known TAG
```

worse case lets just do pagination (it might need to be more than 2 pages but pre-fetch all pages / fetch page by page until found)

**Comment by RamLavi** [comment]
Generally speaking I'm good pagination.

**Comment by RamLavi** [comment]
> what are the two types please ?

There's `annotated tag` and regular `tag`

**Comment by oshoval** [comment]
i wonder if we use annotated tags, and maybe either solution we choose from the ones above will work for both fwiw

**Comment by RamLavi** [comment]
some repos we deploy use annotated, you don't really see it when using `rev-list`..
I'll set a paginating PR soon..

**Comment by oshoval** [comment]
fix for that corner case https://github.com/kubevirt/cluster-network-addons-operator/pull/1817
