### ISSUE TITLE
Fix SonarCloud noise

### ISSUE THREAD

**Issue by oshoval** [kubevirt/cluster-network-addons-operator#1873]
**What happened**:
Stop it from annoyin g on stuff that isnt important for us now,
either open issues / fix or just ignore whatever needed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by oshoval** [comment]
/cc @RamLavi 
if you can please update there what you did, if any leftovers, or we can close it 
thanks

**Comment by RamLavi** [comment]
@oshoval I excluded unit tests files, as done on other kubevirt repos.
closing this, if we encounter with other issues we could address them then
