### ISSUE TITLE
Add openshift scc

### ISSUE THREAD

**Issue by SchSeba** [kubevirt/cluster-network-addons-operator#2]
We need to check if we are running under openshift and add scc configuration for every component

Example
```
Warning  FailedCreate  4m (x22 over 44m)  daemonset-controller  Error creating: pods "kube-multus-ds-amd64-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]
```

**Comment by phoracek** [comment]
Take a look at github.com/nmstate/kubernetes-nmstate. We handle SCC there, we have both the manifest and special 'if' in cluster-sync.

**Comment by SchSeba** [comment]
Yeah I know but we need to implement it inside our operator.
we need to add scc for multus service account and for default service account in the linux-bridge namespace for the linux bridge cni.

**Comment by phoracek** [comment]
Fixed in https://github.com/kubevirt/cluster-network-addons-operator/pull/10
