### ISSUE TITLE
release v0.3.0

### ISSUE THREAD

**Issue by phoracek** [kubevirt/cluster-network-addons-operator#30]
Let's use this issue to track what is needed for the next stable release.

I want #29 in there. It will include kubemacpool and sr-iov that were not shipped in v0.2.0. @SchSeba @booxter are you aware of any must-have fixes? The main use of a new release would be to ship addons operator in hyperconverged-cluster-operator.

**Comment by SchSeba** [comment]
@nikita133 please comment here if you find any issue with the operator

**Comment by phoracek** [comment]
We need to solve https://github.com/kubevirt/cluster-network-addons-operator/issues/33 before releasing or temporarily exclude kubemacpool

**Comment by phoracek** [comment]
We should also include https://github.com/K8sNetworkPlumbingWG/kubemacpool/pull/8. Without it, removal of NetworkAddonsConfig will leave cluster in invalid state where we are unable to create any pods.
