### ISSUE TITLE
Express ContainerRegistry, ContainerTag, and PullPolicy on the operator's CR

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/cluster-network-addons-operator#43]
/kind enhancement

Expose ContainerRegistry, ContainerTag, and PullPolicy on the operator's CR.

HCO's [configuration proposal](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/22)

**Comment by phoracek** [comment]
@rthallisey can we close this with https://github.com/kubevirt/hyperconverged-cluster-operator/pull/40 ?

**Comment by rthallisey** [comment]
yes
