### ISSUE TITLE
versions are wrong at install documentation and /version/version.go

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cluster-network-addons-operator#446]
**What happened**:
The README.md has wrong version at install guide and same happends at version/version.go

**What you expected to happen**:
Correct versions at both things.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by maiqueb** [comment]
Would you define "correct" version ?

**Comment by phoracek** [comment]
We need to get the one that is currently in version.go to the README. From then, our bump script would properly `sed` it on the next bump. I think the README got our of sync in one of the previous releases.
