### ISSUE TITLE
[ref_id:1182]Probes for readiness should succeed [test_id:1200][posneg:positive]with working HTTP probe and http server

### ISSUE THREAD

**Issue by orenc1** [kubevirt/cluster-network-addons-operator#447]
/kind bug
/triage build-officer

**What happened**:
`[ref_id:1182]Probes for readiness should succeed [test_id:1200][posneg:positive]with working HTTP probe and http server
/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Timed out after 60.000s. Expected     <v1.ConditionStatus>: False to equal     <v1.ConditionStatus>: True /root/go/src/kubevirt.io/kubevirt/tests/probes_test.go:82`
[Prow job log](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3726/pull-kubevirt-e2e-k8s-1.18/1278299846477877248)

**Lane:**
pull-kubevirt-e2e-k8s-1.18

**Comment by orenc1** [comment]
/close
@dhiller - why this is appearing on the CNAO flakefinder report page?
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/cluster-network-addons-operator/flakefinder-2020-07-02-024h.html

**Comment by dhiller** [comment]
> /close
> @dhiller - why this is appearing on the CNAO flakefinder report page?
> https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/cluster-network-addons-operator/flakefinder-2020-07-02-024h.html
> 

Because the [job configuration](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml) misses required parameters, `org` and `repo` have to be set, otherwise they both default to `kubevirt`

**Comment by dhiller** [comment]
> > /close
> > @dhiller - why this is appearing on the CNAO flakefinder report page?
> > https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/cluster-network-addons-operator/flakefinder-2020-07-02-024h.html
> > 
> 
> Because the [job configuration](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml) misses required parameters, `org` and `repo` have to be set, otherwise they both default to `kubevirt`
> 
> 

/cc @phoracek @qinqon
