### ISSUE TITLE
Cluster Network Addons Operator when operator in version 0.23.0 is installed and supported spec configured and it is upgraded to the latest release it should report expected deployed container images and leave no leftovers from the previous version

### ISSUE THREAD

**Issue by arnongilboa** [kubevirt/cluster-network-addons-operator#452]
/kind bug
/triage build-officer

**What happened**:

[Fail] Cluster Network Addons Operator when operator in version 0.23.0 is installed and supported spec configured and it is upgraded to the latest release [BeforeEach] it should report expected deployed container images and leave no leftovers from the previous version 

Unexpected error:
    <*errors.errorString | 0xc000962d40>: {
        s: "ObservedVersion \"0.23.0\" does not match expected \"99.0.0\"",
    }
occurred
/tmp/cnao/cluster-network-addons-operator/test/check/check.go:127

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/448/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1280102040420225024

**Comment by ashleyschuett** [comment]
Another failure for 39.3: 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/631/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1324399569236135936

**Comment by dhiller** [comment]
Another one here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/638/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1324380947432345600
