### ISSUE TITLE
[Flaky CI] NetworkAddonsConfig when a config is created should set targetVersion and operatorVersion immediately after it turns Progressing

### ISSUE THREAD

**Issue by awels** [kubevirt/cluster-network-addons-operator#460]
/triage build-officer
/bug
**What happened**:
Flake finder reported failure:
NetworkAddonsConfig when a config is created should set targetVersion and operatorVersion immediately after it turns Progressing

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/448/pull-e2e-cluster-network-addons-operator-workflow-k8s/1281157116526071808

**What you expected to happen**:
Test to pass

**How to reproduce it (as minimally and precisely as possible)**:
See prow job.
**Anything else we need to know?**:

**Environment**:

**Comment by ashleyschuett** [comment]
Another Failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/472/pull-e2e-cluster-network-addons-operator-workflow-k8s/1285124885097484288

**Comment by rhrazdil** [comment]
Addressing in #492
