### ISSUE TITLE
[Flakey CI] Cluster Network Addons Operator when operator in version 0.18.0 is installed and supported spec configured should transition reported versions while being upgraded to version 99.0.0

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/cluster-network-addons-operator#462]
/triage build-officer
/kind bug

**What happened**:
Flakefinder reported the flaky test
```
Cluster Network Addons Operator when operator in version 0.18.0 is installed and supported spec configured should transition reported versions while being upgraded to version 99.0.0
```
In these Prow jobs:
-  [Timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/448/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1280849464193454080)
- [Timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/448/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1280849464193454080)

The timeout appears to be pretty long (20 minutes)

**What you expected to happen**:
The test should pass

**How to reproduce it (as minimally and precisely as possible)**:
See Prow jobs

**Anything else we need to know?**:

**Environment**:

**Comment by dhiller** [comment]
/reopen
/remove-lifecycle rotten

Happened here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/773/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1357214102761508864
