### ISSUE TITLE
[Flakey CI] pull-e2e-cluster-network-addons-operator-workflow-k8s sometimes fails to build the test binary

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/cluster-network-addons-operator#463]
/kind bug
/triage build-officer

**What happened**:
the job `pull-e2e-cluster-network-addons-operator-workflow-k8s` sometimes fail to build the test binary as seen in these jobs:
- [#1](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/450/pull-e2e-cluster-network-addons-operator-workflow-k8s/1282289451682238465)
- [#2](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/456/pull-e2e-cluster-network-addons-operator-workflow-k8s/1282288067188625408)
- [#3](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/457/pull-e2e-cluster-network-addons-operator-workflow-k8s/1282287186770661376)
- [#4](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/449/pull-e2e-cluster-network-addons-operator-workflow-k8s/1282278253259657216)

**What you expected to happen**:
Test should pass
**How to reproduce it (as minimally and precisely as possible)**:
See Prow jobs
**Anything else we need to know?**:

**Environment**:

**Comment by rhrazdil** [comment]
All of these issues are instances of a bug described in https://github.com/kubevirt/cluster-network-addons-operator/issues/451, which was already addressed.
I think we can close this @phoracek ?

**Comment by phoracek** [comment]
Sounds right, thanks!
