### ISSUE TITLE
Check objects recovery should be able to recover from service secret deletion

### ISSUE THREAD

**Issue by awels** [kubevirt/cluster-network-addons-operator#502]
/bug
/triage build-officer

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/499/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1292880592978841601

/tmp/deploy.kubemacpool.Xkyu/github.com/k8snetworkplumbingwg/kubemacpool/tests/certificates_test.go:23
Should successfully get pre test secret
Unexpected error:
    <*errors.StatusError | 0xc0002005a0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "secrets \"kubemacpool-service\" not found",
            Reason: "NotFound",
            Details: {
                Name: "kubemacpool-service",
                Group: "",
                Kind: "secrets",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    secrets "kubemacpool-service" not found
occurred
/tmp/deploy.kubemacpool.Xkyu/github.com/k8snetworkplumbingwg/kubemacpool/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:43
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by brybacki** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/501/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1293158108062814208
