### ISSUE TITLE
[Flakey CI] Cluster Network Addons Operator when operator in version 0.39.3 is installed and supported spec configured [BeforeEach] should transition reported versions while being upgraded to version 99.0.0

### ISSUE THREAD

**Issue by shwetaap** [kubevirt/cluster-network-addons-operator#508]
/triage build-officer
/kind bug

**What happened**:
Flakefinder reported the flakey test

Cluster Network Addons Operator when operator in version 0.39.3 is installed and supported spec configured should transition reported versions while being upgraded to version 99.0.0

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/500/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1292907017362477056

**What you expected to happen**:
Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by ashleyschuett** [comment]
Another failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/633/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1321330618755190784

**Comment by dhiller** [comment]
Another failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/638/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1325742039886729216

**Comment by RamLavi** [comment]
recreated [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/804/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1373614692420816897)
/reopen
