### ISSUE TITLE
[flaky CI] NetworkAddonsConfig when a valid config is deployed and a component which does support removal is removed from the Spec should remain at Available condition 

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cluster-network-addons-operator#523]
**What happened**:
Following CI job failing on unrelated issue

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/522/pull-e2e-cluster-network-addons-operator-workflow-k8s/1301099059494260737

Issue is related to kubemacpool mac range 

```
      - type: Degraded
        status: "False"
        reason: FailedToValidate
        message: |-
          failed to validate NetworkConfig.Spec: invalid configuration:
          both or none of the KubeMacPool ranges needs to be configured: invalid configuration:
          both or none of the KubeMacPool ranges needs to be configured
        lastheartbeattime: "2020-09-02T10:24:03Z"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

/kind bug
/triage build-officer

**Comment by phoracek** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/522/pull-e2e-cluster-network-addons-operator-workflow-k8s/1301099059494260737

**Comment by orenc1** [comment]
Another recurrence today:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/541/pull-e2e-cluster-network-addons-operator-workflow-k8s/1304146640625471489

**Comment by qinqon** [comment]
another
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/539/pull-e2e-cluster-network-addons-operator-workflow-k8s/1305072741505830912

**Comment by brybacki** [comment]
Tyoday fails together with :"NetworkAddonsConfig when invalid config is applied and it is updated with a valid config should turn from Failing to Available"

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/539/pull-e2e-cluster-network-addons-operator-workflow-k8s/1304091151027933184

**Comment by RamLavi** [comment]
Fixed in #547 and test added to catch sooner in #551

**Comment by phoracek** [comment]
Would you please close this Issue if it was indeed solved? You should now have access to do so.

**Comment by RamLavi** [comment]
@phoracek I thought the bot closes it when I mention it fixes it.

anyway I added a specific PR to fix this. #573
will close after it is merged

**Comment by RamLavi** [comment]
#573 merged. closing issue

**Comment by RamLavi** [comment]
issue is [not resolved](https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/582/pull-e2e-cluster-network-addons-operator-workflow-k8s/1311241891164983296). reopening.

**Comment by awels** [comment]
Another instance: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/628/pull-e2e-cluster-network-addons-operator-workflow-k8s/1320732933832577024

**Comment by ashleyschuett** [comment]
Another failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/640/pull-e2e-cluster-network-addons-operator-workflow-k8s/1323882410424668160
