### ISSUE TITLE
fighting over bridge and plugins path on OpenShift 4

### ISSUE THREAD

**Issue by phoracek** [kubevirt/cluster-network-addons-operator#55]
Network operator on OpenShift 4 is deploying binaries of CNI plugins, including `bridge` and `tuning`. Our addons operator is trying to deploy different version of `bridge` and `tuning` to the same path. Therefore, there is a race for the spot, who is slower, wins.

We have to tackle this issue, maybe by adding a `kubevirt-` prefix to our binaries.

**Comment by phoracek** [comment]
CC @SchSeba

**Comment by phoracek** [comment]
@booxter could you please fix this with the same way it has been done for SR-IOV (with the environment variable)? If you find some spare time. Thanks

**Comment by booxter** [comment]
@phoracek considering the discussion we had today, is this issue still of interest to us? I am told that CNV images already contain the plugin binaries renamed, so cp *tuning should already take care of the custom name for the plugins shipped as part of CNV.

Now, I may see an argument for reverting the renaming of the binaries inside the CNV images and instead using manifests to control result name for them like we do for SR-IOV CNI binary; which would get rid of yet another difference between upstream and CNV container images. Is it something we want to pursue?

**Comment by phoracek** [comment]
@booxter I'd like to keep it consistent. Otherwise, I'm sure I will forget about it again and make noise next time this will be a topic. However, I would postpone this change, let's not change what works until we resolve more urgent issues.

**Comment by phoracek** [comment]
Things changed since we opened this bug. Closing for now, we can re-evaluate later.
