### ISSUE TITLE
[Flaky CI]  [rfe_id:3503][crit:medium][vendor:cnv-qe@redhat.com][level:component]Virtual Machines Check the client When all the VMs are serviced by default (opt-out mode) and we re-apply a VM yaml [test_id:2243]should assign to the VM the same MAC addresses as before the re-apply, and not return an error

### ISSUE THREAD

**Issue by rhrazdil** [kubevirt/cluster-network-addons-operator#552]
**What happened**:
Test failed on tier 1 kubemacpool test lane:
https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/548/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1305843446665187328

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by RamLavi** [comment]
addressed in [KMP PR](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/245)
will be fixed in next KMP bump

**Comment by RamLavi** [comment]
fixed in #564

**Comment by RamLavi** [comment]
fixed in #565
