### ISSUE TITLE
[flaky ci] [rfe_id:3503][crit:medium][vendor:cnv-qe@redhat.com][level:component]Virtual Machines Check the client When Running with default opt-mode configuration and a VM's NIC is removed and a new VM is created with the same MAC [test_id:2995]should successfully release the MAC and the new VM should be created with no errors

### ISSUE THREAD

**Issue by dhiller** [kubevirt/cluster-network-addons-operator#653]
**What happened**:

Test `[rfe_id:3503][crit:medium][vendor:cnv-qe@redhat.com][level:component]Virtual Machines Check the client When Running with default opt-mode configuration and a VM's NIC is removed and a new VM is created with the same MAC [test_id:2995]should successfully release the MAC and the new VM should be created with no errors` flaked before PR #649 got merged

Failing run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/649/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1326131103655792641

PR history: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=cluster-network-addons-operator&pr=649

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

/kind bug
/triage build-watcher

**Comment by phoracek** [comment]
@RamLavi are we looking into this one already?

**Comment by RamLavi** [comment]
>@RamLavi are we looking into this one already?

@phoracek yes, an issue is already open on KMP: https://github.com/k8snetworkplumbingwg/kubemacpool/issues/249

**Comment by RamLavi** [comment]
once #670 is merged we'll have more light on what happens when it flakes.

**Comment by RamLavi** [comment]
update: this is the false error we get: [prow](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/675/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1331288692093882369#1:build-log.txt%3A5489)
```
Message: "admission webhook \"mutatevirtualmachines.kubemacpool.io\" denied the request: Failed to create virtual machine allocation error: Failed to allocate mac to the vm object: failed to allocate requested mac address"
```

**Comment by RamLavi** [comment]
After investigating, it looks like a wrong error was expected in KMP.
posted a [PR](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/255) to fix

**Comment by dhiller** [comment]
/close

Closing this as fix brought in by k8snetworkplumbingwg/kubemacpool#255 was merged.
