### ISSUE TITLE
[flaky CI]  NodeNetworkConfigurationPolicy bonding default interface when there is a default interface with dynamic address should successfully move default IP address on top of the bond

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cluster-network-addons-operator#663]
**What happened**:

Current jobs related to knmstate is failing:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/660/pull-e2e-cluster-network-addons-operator-nmstate-functests/1326895389139275777

/kind bug
/triage build-watcher

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/636/pull-kubernetes-nmstate-e2e-handler-k8s/1327249346046988288
