### ISSUE TITLE
Autobumper has failed to pin new nmstate version

### ISSUE THREAD

**Issue by phoracek** [kubevirt/cluster-network-addons-operator#693]
**What happened**:

knmstate 0.35 was released but (unlike the bridge-marker) it was not picked up by CNAO automation.

I see one failing Actions job in the history: https://github.com/kubevirt/cluster-network-addons-operator/runs/1528591039?check_suite_focus=true

**Comment by RamLavi** [comment]
@phoracek, knmstate wasn't picked because linux-bridge bump failed, causing the bumper script to stop.
I initially thought it would be best to stop the bumper script at the first bump failure, do you think we should change that?

**Comment by phoracek** [comment]
I see.

If the failure is caused by the vendored sub-component and not us, we should continue with the process and at the end mark the job as failed (but bump as many components as we can). We can get into a situation where we really need knmstate bumped, but another sub-component is broken.

If the failure is caused by CNAO, then we should fix it ASAP, but I don't think we'd need to gracefully ignore part of our (CNAO's) fails.

**Comment by RamLavi** [comment]
fixed. closing issue
