### ISSUE TITLE
[flaky ci] NodeNetworkConfigurationPolicy bonding default interface when there is a default interface with dynamic address should successfully move default IP address on top of the bond

### ISSUE THREAD

**Issue by dhiller** [kubevirt/cluster-network-addons-operator#703]
**What happened**:

/triage build-watcher
/kind bug

Test `NodeNetworkConfigurationPolicy bonding default interface when there is a default interface with dynamic address should successfully move default IP address on top of the bond` flaked on PRs:
* https://github.com/kubevirt/cluster-network-addons-operator/pull/692
* https://github.com/kubevirt/cluster-network-addons-operator/pull/696
* https://github.com/kubevirt/cluster-network-addons-operator/pull/698

Runs:
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/698/pull-e2e-cluster-network-addons-operator-nmstate-functests/1339542045194194945
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338742179325022208
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338604779537960960
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338521466483773440
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338499697693691904
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/692/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338135321635721217

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
/tmp/deploy.nmstate.nPdr/github.com/nmstate/kubernetes-nmstate/test/e2e/handler/bonding_default_interface_test.go:49
Timed out after 480.000s.
Expected
    <shared.ConditionList | len:2, cap:2>: [
        {
            Type: "Available",
            Status: "False",
            Reason: "",
            Message: "",
            LastHeartbeatTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
        },
        {
            Type: "Degraded",
            Status: "True",
            Reason: "",
            Message: "",
            LastHeartbeatTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
        },
    ]
to contain element matching
    <shared.Condition>: {
        Type: "Available",
        Status: "True",
        Reason: "",
        Message: "",
        LastHeartbeatTime: {
            Time: 0001-01-01T00:00:00Z,
        },
        LastTransitionTime: {
            Time: 0001-01-01T00:00:00Z,
        },
    }
/tmp/deploy.nmstate.nPdr/github.com/nmstate/kubernetes-nmstate/test/e2e/handler/conditions.go:13
```

```
/tmp/deploy.nmstate.Odmb/github.com/nmstate/kubernetes-nmstate/test/e2e/handler/bonding_default_interface_test.go:49
Timed out after 480.000s.
Expected
    <shared.ConditionList | len:2, cap:2>: [
        {
            Type: "Available",
            Status: "False",
            Reason: "",
            Message: "",
            LastHeartbeatTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
        },
        {
            Type: "Degraded",
            Status: "True",
            Reason: "",
            Message: "",
            LastHeartbeatTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
        },
    ]
to contain element matching
    <shared.Condition>: {
        Type: "Available",
        Status: "True",
        Reason: "",
        Message: "",
        LastHeartbeatTime: {
            Time: 0001-01-01T00:00:00Z,
        },
        LastTransitionTime: {
            Time: 0001-01-01T00:00:00Z,
        },
    }
/tmp/deploy.nmstate.Odmb/github.com/nmstate/kubernetes-nmstate/test/e2e/handler/conditions.go:133
```

**Environment**:

**Comment by RamLavi** [comment]
FYI, this is a tier1 representation of a known [flaky](https://github.com/nmstate/kubernetes-nmstate/issues/569) in knmstate:

**Comment by qinqon** [comment]
Closes by https://github.com/kubevirt/cluster-network-addons-operator/pull/712

**Comment by RamLavi** [comment]
is it back? prow [link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/727/pull-e2e-cluster-network-addons-operator-nmstate-functests/1347188092745814016)

if not, feel free to re-close the issue

**Comment by qinqon** [comment]
@RamLavi Are we sure it's happening still at master branch ? in case of stable branch we may need to backport some e2e test fixes at knmstate
