### ISSUE TITLE
[flaky ci] NodeNetworkState when desiredState is configured with the bond interface as linux bridge port should have the bond in the linux bridge as port at currentState

### ISSUE THREAD

**Issue by dhiller** [kubevirt/cluster-network-addons-operator#704]
**What happened**:

/triage build-watcher
/kind bug

Test `NodeNetworkState when desiredState is configured with the bond interface as linux bridge port should have the bond in the linux bridge as port at currentState` flaked at PRs:
* https://github.com/kubevirt/cluster-network-addons-operator/pull/696
* https://github.com/kubevirt/cluster-network-addons-operator/pull/698

Failing runs:
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/698/pull-e2e-cluster-network-addons-operator-nmstate-functests/1339542045194194945
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338742179325022208
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338604779537960960
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338560659448664064
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/696/pull-e2e-cluster-network-addons-operator-nmstate-functests/1338537410912325632

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
/tmp/deploy.nmstate.nPdr/github.com/nmstate/kubernetes-nmstate/test/e2e/handler/simple_bridge_and_bond_test.go:183
Timed out after 480.000s.
Expected
    <shared.ConditionList | len:2, cap:2>: [
        {
            Type: "Available",
            Status: "False",
            Reason: "",
            Message: "",
            LastHeartbeatTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
        },
        {
            Type: "Degraded",
            Status: "True",
            Reason: "",
            Message: "",
            LastHeartbeatTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
        },
    ]
to contain element matching
    <shared.Condition>: {
        Type: "Available",
        Status: "True",
        Reason: "",
        Message: "",
        LastHeartbeatTime: {
            Time: 0001-01-01T00:00:00Z,
        },
        LastTransitionTime: {
            Time: 0001-01-01T00:00:00Z,
        },
    }
/tmp/deploy.nmstate.nPdr/github.com/nmstate/kubernetes-nmstate/test/e2e/handler/conditions.go:133
```

**Environment**:

**Comment by alonSadan** [comment]
happened again: 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/669/pull-kubernetes-nmstate-e2e-handler-k8s-future/1340990724841148416

**Comment by qinqon** [comment]
Closes by https://github.com/nmstate/kubernetes-nmstate/pull/657

Also future lane issue is different and will be close by https://github.com/nmstate/kubernetes-nmstate/pull/661

**Comment by qinqon** [comment]
We can ignore future lane since it's a non requiered lane and there is a PR to fix it.
