### ISSUE TITLE
[flaky CI][rfe_id:3503][crit:medium][vendor:cnv-qe@redhat.com][level:component]Virtual Machines Check the client When Running with default opt-mode configuration and a VM's NIC is removed and a new VM is created with the same MAC [test_id:2995]should successfully release the MAC and the new VM should be created with no errors

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cluster-network-addons-operator#720]
**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/708/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1341033132257710081

/kind bug
/triage build-watcher

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by AlonaKaplan** [comment]
Another link to the same error-
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/718/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1341655526152343552

**Comment by RamLavi** [comment]
it seems that an old webhook request is re-enqueued, returning the mac to the internal cache.

**Comment by brybacki** [comment]
seen again in #727, #730, #729

**Comment by borod108** [comment]
/reopen
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/762/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1354745587022434304

**Comment by dhiller** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/708/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1341033132257710081
