### ISSUE TITLE
NodeNetworkConfigurationPolicy default bridged network when there is a default interface with dynamic address and linux bridge is configured on top of the default interface should keep the default IP address after node reboot

### ISSUE THREAD

**Issue by arnongilboa** [kubevirt/cluster-network-addons-operator#758]
/triage build-watcher
/kind bug

**What happened**:
`NodeNetworkConfigurationPolicy default bridged network when there is a default interface with dynamic address and linux bridge is configured on top of the default interface should keep the default IP address after node reboot`

logs [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/757/pull-e2e-cluster-network-addons-operator-nmstate-functests/1353287856105197569)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by nelsonspbr** [comment]
Occurred again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/769/pull-e2e-cluster-network-addons-operator-nmstate-functests/1356477372043366401

**Comment by phoracek** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/783/pull-e2e-cluster-network-addons-operator-nmstate-functests/1359024656824143873
