### ISSUE TITLE
development documentation in README.md is incorrect

### ISSUE THREAD

**Issue by sjpotter** [kubevirt/cluster-network-addons-operator#87]
It says

> generate sources (requires operator-sdk installed on your host)
> operator-sdk generate k8s

but if one tries that, one gets

> $ operator-sdk generate k8s
> FATA[0000] Must run command in project root dir: project structure requires ./build/Dockerfile

if one moves ./build/operator/Dockerfile to ./build/ it "seems" to work, but don't know if that's correct.

**Comment by SchSeba** [comment]
I think this PR https://github.com/kubevirt/cluster-network-addons-operator/pull/88 should fix the issue

**Comment by phoracek** [comment]
Thanks for reporting this.

In long term, we should replace `operator-sdk generate k8s` with Kubernetes code-generator (or make this project complatible with operator-sdk again, but I hate the boilerplate).

However, if #88 fixed the problem for you @sjpotter, please close this issue.

**Comment by sjpotter** [comment]
works, but as noted there operator-sdk removes the apache license at the top of the generated code.

**Comment by phoracek** [comment]
We need a separate PR to fix our license headers everywhere. Closing the issue. Thanks for reporting and testing!
