### ISSUE TITLE
Possible wrong logic on checkForGenericDeployment

### ISSUE THREAD

**Issue by oshoval** [kubevirt/cluster-network-addons-operator#875]
At `checkForGenericDeployment` , in case `checkLabels` is true
(controls logic of `labels[cnaov1.SchemeGroupVersion.Group+"/version"]` checking),
there is no handling to the case of labels == nil, that might need to return error
Need to understand why, and fix if needed

**Comment by RamLavi** [comment]
I think this is sorted out here https://github.com/kubevirt/cluster-network-addons-operator/pull/942
closing. @oshoval FYI
