### ISSUE TITLE
correct version, provider and name

### ISSUE THREAD

**Issue by alexxa** [kubevirt/cluster-network-addons-operator#90]
I have just tried to deploy cna-operator following [ReadMe - Deploy using OLM](https://github.com/kubevirt/cluster-network-addons-operator#deploy-using-olm) and using [this image](https://hub.docker.com/r/djzager/cna-registry/tags).
In the Web UI, I see that

- There is no 'Operator' in the name in Operators Catalog. I don't know if there is any spec for operators naming and if it should be there or not. 
- version 0.0.0
- "provided by KubeVirt project". Should it be "Red Hat", maybe?
![Screenshot from 2019-04-30 14-17-31](https://user-images.githubusercontent.com/6319198/56961149-44aa9b80-6b53-11e9-8326-2fd793b390c3.jpg)

**Comment by phoracek** [comment]
Thanks for reporting this @alexxa.

@SchSeba if you find some time, would you please look into it? For the name, we should check on KubeVirt and CDI operators, it there is an agreement on ' Operator'. The same for 'provided by'.

The problem with the version is, that the cna-registry is outdated (22 days old). @alexxa could you try to use https://quay.io/repository/kubevirt/cluster-network-addons-registry?tab=tags? With 0.5.0 tag.

**Comment by SchSeba** [comment]
I will take a look on that

btw I am unfamiliar with the image you used https://hub.docker.com/r/djzager/cna-registry/tags
@phoracek ?

Our images are under quay.io inside the kubevirt organization.

**Comment by SchSeba** [comment]
I check the HCO and there is the file https://github.com/kubevirt/hyperconverged-cluster-operator/pull/46/files#diff-d18084c4431837e68157c7948d3b17b9R28

they use `publisher: Red Hat` same as us

**Comment by phoracek** [comment]
/remove-lifecycle stale

Should be verified.
